server:
    port: 8082
spring:
    application: 
        name: product_api
    datasource:
        url: "jdbc:postgresql://localhost:5433/product_db"
        username: "admin"
        password: "123456"
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update 
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            
