name: "Development Workflow"
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: "Get Code"
            uses: actions/checkout@v3

          - name: "Install NodeJs"
            uses: actions/setup-node@v3
            with: 
                node-version: 18
                cache: yarn
            
          - name: "Install Application"
            run: yarn install --frozen-lockfile
          
          - name: "Test Application"
            run: yarn test

          - name: "Build Application"
            run: yarn build
